### ISSUE TITLE
.xcworkspace 打包报错

### ISSUE THREAD

**Issue by zhangchangrui** [stackhou/AutoPacking-iOS#11]
** ARCHIVE FAILED **

The following build commands failed:
	Ld /Users/edaobao/Library/Developer/Xcode/DerivedData/AutoPackingDemo-ggclroqhawoqkrbfupxglfycilxo/Build/Intermediates.noindex/ArchiveIntermediates/AutoPackingDemo/IntermediateBuildFilesPath/AutoPackingDemo.build/Debug-iphoneos/AutoPackingDemo.build/Objects-normal/arm64/AutoPackingDemo normal arm64
(1 failure)

********* 项目构建失败 😢 😢 😢 ***************

**Comment by stackhou** [comment]
前提是手动也能打包，你这个需要配置一下
