### ISSUE TITLE
打包失败

### ISSUE THREAD

**Issue by huangyingqiu** [stackhou/AutoPacking-iOS#14]
![2018-12-07 1 06 32](https://user-images.githubusercontent.com/17267413/49632780-e6f5a580-fa31-11e8-8aef-71318bb94842.png)

**Comment by huangyingqiu** [comment]
提示很模糊，不知道哪里出了问题

**Comment by stackhou** [comment]
这是xcodebuild 报错，给xcode 提个建议吧
