### ISSUE TITLE
脚本中变量未定义,直接使用.

### ISSUE THREAD

**Issue by MrDML** [stackhou/AutoPacking-iOS#19]
![Snip20190323_1](https://user-images.githubusercontent.com/17716198/54864475-01f6e600-4d93-11e9-80f2-b86cd77da745.png)
![Snip20190323_2](https://user-images.githubusercontent.com/17716198/54864477-058a6d00-4d93-11e9-98c3-8c0a7310a200.png)

**Comment by trc19930224** [comment]
确实存在这样的问题，导致报错：xcodebuild: error: Unknown build action，不知道其他人是怎么一次运行成功的

**Comment by stackhou** [comment]
这个需要自己配置一下
