### ISSUE TITLE
default info.plist file direction is not configurable

### ISSUE THREAD

**Issue by LeeLyonse** [stackhou/AutoPacking-iOS#2]
# 已经指定Target的Info.plist文件路径
__CURRENT_INFO_PLIST_NAME="${__SCHEME_NAME}-Info.plist"
# 获取 Info.plist 路径
__CURRENT_INFO_PLIST_PATH="${__PROJECT_NAME}/Configs/${__CURRENT_INFO_PLIST_NAME}"

the "Configs " path should be configurable, right?

**Comment by stackhou** [comment]
Configs is the folder where I put Info.plist, and you can configure it according to where you actually put it in Info.plist

**Comment by Anyeler** [comment]
=== BUILD TARGET AliyunOSSiOS OF PROJECT Pods WITH CONFIGURATION Release ===
Check dependencies
Code Signing Error: AliyunOSSiOS does not support provisioning profiles. AliyunOSSiOS does not support provisioning profiles, but provisioning profile NO_SIGNING/ has been manually specified. Set the provisioning profile value to "Automatic" in the build settings editor.

pod里面有很多这种情况怎么处理
