### ISSUE TITLE
多个Target能打包吗

### ISSUE THREAD

**Issue by biostome** [stackhou/AutoPacking-iOS#20]
多个Target能打包吗，看了下第86行，只知道写一个，多个这么写？

**Comment by stackhou** [comment]
# 1. 请选择 SCHEME
__SELECT_TARGET_OPTIONS=("1.AutoPackingDemo")
READ_USER_INPUT "请选择对应的Target: " "${__SELECT_TARGET_OPTIONS[*]}" ${#__SELECT_TARGET_OPTIONS[*]}

__SELECT_TARGET_OPTION=$?
if [[ $__SELECT_TARGET_OPTION -eq 1 ]]; then
  __BUILD_TARGET="AutoPackingDemo"
else
  printMessage "这里请填写好你工程的所有target, 如果只有一个建议写死如下"
  # __BUILD_TARGET="AutoPackingDemo"
  exit 1
fi


__SELECT_TARGET_OPTIONS 这个变量是数组，把您的所有target写在这里，然后下面if else 判断添加你的target就可以了
