### ISSUE TITLE
 BUILD TARGETS OF PROJECT Pods WITH CONFIGURATION Release

### ISSUE THREAD

**Issue by Anyeler** [stackhou/AutoPacking-iOS#4]
=== BUILD TARGET AliyunOSSiOS OF PROJECT Pods WITH CONFIGURATION Release ===
Check dependencies
Code Signing Error: AliyunOSSiOS does not support provisioning profiles. AliyunOSSiOS does not support provisioning profiles, but provisioning profile NO_SIGNING/ has been manually specified. Set the provisioning profile value to "Automatic" in the build settings editor.

How to deal with these problems?

**Comment by LeeLyonse** [comment]
open the pods project. And config all the targets with the automatically manage signing clicked!
