### ISSUE TITLE
Xcode9.4打包出现下面问题，scheme已设置无误

### ISSUE THREAD

**Issue by zhonggaorong** [stackhou/AutoPacking-iOS#9]
User defaults from command line:
    IDEArchivePathOverride = /Users/zhonggaorong/ios/RedEnvelopes/build/xxxxx.xcarchive

Build settings from command line:
    CFBundleVersion = File
    CODE_SIGN_IDENTITY = iPhone Developer:xxxxxxxxxxxx(xxxxxx)

xcodebuild: error: Unknown build action 'Doesn't'.

********* 项目构建失败 😢 😢 😢 ***************

**Comment by MrzYc** [comment]
能不能给个参考样式呀我也是不知道怎么配置

**Comment by stackhou** [comment]
已经添加demo，需要更换的地方：1. 你的Bundle identifier 2.还有Plist里面的相应plist文件，3、上传蒲公英或者Fir的相关APPID和Key，4.(可选) 如果是多个证书的话，需要指定证书，并打开下面的注释

**Comment by ClearSun** [comment]
![image](https://user-images.githubusercontent.com/14053806/46080991-f654a900-c1cd-11e8-8b93-92c0ec881d9c.png)
Print: Entry, "CFBundleShortVersionString", Does Not Exist
Print: Entry, "CFBundleVersion", Does Not Exist


请问这个是哪里出问题了？

**Comment by stackhou** [comment]
这个是我的Demo吗？Info.plist 的路径配置不对？看看Demo的配置
